version: '3.4'

services:
  tickets_app:
    container_name: tickets_app_ssr
    build:
      context: .
      target: 'build-stage'
      dockerfile: .docker/ssr.test.Dockerfile
    volumes:
      - .:/app
    ports:
      - '34518:80'
    command: /bin/sh -c "yarn && quasar dev -m ssr"
