module.exports = () => {
  return [
    {
      eventID: 11653,
      eventTitle: 'A Possessão De Mary',
      trailerURL:
        'https://www.youtube.com/embed/gHoR5sJRE6s?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1',
      eventComingSoon: false,
      complementaryText: 'EM CARTAZ',
      highlightedText: '',
      highlighted: false,
      debut: false,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/a-possessao-de-mary_11653_home.jpg?20011511',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/A-Possessao-De-Mary/11653',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/A-Possessao-De-Mary/11653',
      promoTickets: false,
      distributor: 'Grupo Paris Filmes',
      genre: 'Terror',
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 8114,
      eventTitle: 'John Wick 3 - Parabellum',
      trailerURL:
        'https://www.youtube.com/embed/JNK5y5viwmQ?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1',
      eventComingSoon: false,
      complementaryText: 'EM CARTAZ',
      highlightedText: '',
      highlighted: false,
      debut: false,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/john-wick-3-parabellum_8114_home.jpg?19043923',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/John-Wick-3-Parabellum/8114',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/John-Wick-3-Parabellum/8114',
      promoTickets: false,
      distributor: 'Grupo Paris Filmes',
      genre: 'Ação',
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 9167,
      eventTitle: 'Casal Improvável',
      trailerURL:
        'https://www.youtube.com/embed/1OmHBuFWUFY?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1',
      eventComingSoon: false,
      complementaryText: 'EM CARTAZ',
      highlightedText: '',
      highlighted: false,
      debut: false,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/casal-improvavel_9167_home.jpg?19052506',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Casal-Improvavel/9167',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Casal-Improvavel/9167',
      promoTickets: false,
      distributor: 'Grupo Paris Filmes',
      genre: 'Comédia Romantica',
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 11625,
      eventTitle: 'Tenet',
      trailerURL:
        'https://www.youtube.com/embed/kbIw8H1JjPk?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 10/09/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/tenet_11625_home.jpg?19123508',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Tenet/11625',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Tenet/11625',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12423,
      eventTitle: 'Um Lugar Silencioso: Parte I e II (Especial Belas Artes)',
      trailerURL: '',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 13/09/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/um-lugar-silencioso-parte-i-e-ii-especial-belas-artes_12423_home.jpg?20035014',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/Um-Lugar-Silencioso-Parte-I-e-II-Especial-Belas-Artes/12423',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/Um-Lugar-Silencioso-Parte-I-e-II-Especial-Belas-Artes/12423',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 7995,
      eventTitle: 'Mulher-Maravilha 1984',
      trailerURL:
        'https://www.youtube.com/embed/1c8q87mTgzg?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 01/10/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/mulher-maravilha-1984_7995_home.jpg?20030016',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Mulher-Maravilha-1984/7995',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Mulher-Maravilha-1984/7995',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 11311,
      eventTitle: 'Viúva Negra',
      trailerURL:
        'https://www.youtube.com/embed/OG5TZp_iBGY?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 29/10/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/viuva-negra_11311_home.jpg?20033509',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Viuva-Negra/11311',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Viuva-Negra/11311',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 11519,
      eventTitle: 'Free Guy - Assumindo o Controle',
      trailerURL:
        'https://www.youtube.com/embed/squDUxVyGoQ?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 10/11/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/free-guy-assumindo-o-controle_11519_home.jpg?20010032',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/Free-Guy-Assumindo-o-Controle/11519',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/Free-Guy-Assumindo-o-Controle/11519',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 8015,
      eventTitle: '007 - Sem Tempo Para Morrer',
      trailerURL:
        'https://www.youtube.com/embed/YYH39bvu-Uc?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 19/11/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/007-sem-tempo-para-morrer_8015_home.jpg?20014014',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/007-Sem-Tempo-Para-Morrer/8015',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/007-Sem-Tempo-Para-Morrer/8015',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12375,
      eventTitle: 'Godzilla vs. Kong',
      trailerURL: '',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 19/11/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/godzilla-vs--kong_12375_home.jpg?20033009',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Godzilla-vs--Kong/12375',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Godzilla-vs--Kong/12375',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12235,
      eventTitle: 'Invasão Zumbi 2: Península',
      trailerURL:
        'https://www.youtube.com/embed/bR8aQ9IZJPE?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 12/12/2020',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/invasao-zumbi-2-peninsula_12235_home.jpg?20043507',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/Invasao-Zumbi-2-Peninsula/12235',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/Invasao-Zumbi-2-Peninsula/12235',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 11861,
      eventTitle: 'Velozes e Furiosos 9',
      trailerURL:
        'https://www.youtube.com/embed/fTuvyx5krsI?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 01/04/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/velozes-e-furiosos-9_11861_home.jpg?20013013',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Velozes-e-Furiosos-9/11861',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Velozes-e-Furiosos-9/11861',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 11613,
      eventTitle: 'Um Lugar Silencioso - Parte II',
      trailerURL:
        'https://www.youtube.com/embed/sEv0u_DdkEM?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 22/04/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/um-lugar-silencioso-parte-ii_11613_home.jpg?20020509',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/Um-Lugar-Silencioso-Parte-II/11613',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/Um-Lugar-Silencioso-Parte-II/11613',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12433,
      eventTitle: 'Venom 2',
      trailerURL: '',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 24/06/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/venom-2_12433_home.jpg?20044508',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Venom-2/12433',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Venom-2/12433',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12437,
      eventTitle: 'Minions 2: A Origem de Gru',
      trailerURL: '',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 01/07/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/minions-2-a-origem-de-gru_12437_home.jpg?20040508',
      moviePage:
        '/Portal/Evento/Cinema/Santa-Ines/Minions-2-A-Origem-de-Gru/12437',
      buyClick:
        '/Portal/Evento/Cinema/Santa-Ines/Minions-2-A-Origem-de-Gru/12437',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 7827,
      eventTitle: 'Top Gun: Maverick',
      trailerURL:
        'https://www.youtube.com/embed/8b83aU7x-7c?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 08/07/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/top-gun-maverick_7827_home.jpg?19073009',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Top-Gun-Maverick/7827',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Top-Gun-Maverick/7827',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
    {
      eventID: 12429,
      eventTitle: 'Trolls 2',
      trailerURL:
        'https://www.youtube.com/embed/77qjS4bw7bY?controls=1&wmode=transparent&rel=0&showinfo=0&enablejsapi=1&modestbranding=1&cc_load_policy=0&html5=1&widgetid=1&enablejsapi=1',
      eventComingSoon: true,
      complementaryText: 'Em breve',
      highlightedText: 'Lançamento 08/08/2021',
      highlighted: false,
      debut: true,
      posterImage:
        'https://img.veloxtickets.com/content/titulos/home/trolls-2_12429_home.jpg?20032507',
      moviePage: '/Portal/Evento/Cinema/Santa-Ines/Trolls-2/12429',
      buyClick: '/Portal/Evento/Cinema/Santa-Ines/Trolls-2/12429',
      promoTickets: false,
      categoryName: 'Padrão',
      categoryOrder: '-99',
    },
  ];
};
